name = "sender-cron"
main = "sender.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
# svakih 10 minuta
crons = ["*/10 * * * *"]

[vars]
SENDER_BASE_URL = "https://whatsapp-message-sender-blond.vercel.app"
