name = "sender-cron"
main = "sender.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["9 15 * * *"]

[vars]
SENDER_BASE_URL = "https://whatsapp-message-sender-ony3.onrender.com"

[observability.logs]
enabled = true
