name = "sender-pinger-cron"
main = "pinger.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
PINGER_BASE_URL = "https://whatsapp-message-sender-ony3.onrender.com"

[observability.logs]
enabled = true
